plugin_dirs = [
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files/Common Files/CLAP',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files/Common Files/VST2',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files/Common Files/VST3',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files/Steinberg/VSTPlugins',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files/VstPlugins',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files (x86)/Common Files/VST2',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files (x86)/Common Files/VST3',
    '/home/l1npengtul/.local/share/bottles/bottles/plugins/drive_c/Program Files (x86)/Steinberg/VSTplugins',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []
